(cl:defpackage comp313p_mapper-srv
  (:use )
  (:export
   "CHANGEMAPPERSTATE"
   "<CHANGEMAPPERSTATE-REQUEST>"
   "CHANGEMAPPERSTATE-REQUEST"
   "<CHANGEMAPPERSTATE-RESPONSE>"
   "CHANGEMAPPERSTATE-RESPONSE"
   "REQUESTMAPUPDATE"
   "<REQUESTMAPUPDATE-REQUEST>"
   "REQUESTMAPUPDATE-REQUEST"
   "<REQUESTMAPUPDATE-RESPONSE>"
   "REQUESTMAPUPDATE-RESPONSE"
  ))

