// Generated by gencpp from file comp313p_mapper/RequestMapUpdateRequest.msg
// DO NOT EDIT!


#ifndef COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATEREQUEST_H
#define COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comp313p_mapper
{
template <class ContainerAllocator>
struct RequestMapUpdateRequest_
{
  typedef RequestMapUpdateRequest_<ContainerAllocator> Type;

  RequestMapUpdateRequest_()
    : deltaOccupancyGridRequired(false)  {
    }
  RequestMapUpdateRequest_(const ContainerAllocator& _alloc)
    : deltaOccupancyGridRequired(false)  {
  (void)_alloc;
    }



   typedef uint8_t _deltaOccupancyGridRequired_type;
  _deltaOccupancyGridRequired_type deltaOccupancyGridRequired;





  typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestMapUpdateRequest_

typedef ::comp313p_mapper::RequestMapUpdateRequest_<std::allocator<void> > RequestMapUpdateRequest;

typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateRequest > RequestMapUpdateRequestPtr;
typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateRequest const> RequestMapUpdateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comp313p_mapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'comp313p_mapper': ['/home/victor/COMP313P/cw1_ws/src/comp313p/comp313p_mapper/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7f3f7638aa1640753832d43db8a1853";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7f3f7638aa16407ULL;
  static const uint64_t static_value2 = 0x53832d43db8a1853ULL;
};

template<class ContainerAllocator>
struct DataType< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comp313p_mapper/RequestMapUpdateRequest";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool deltaOccupancyGridRequired\n\
";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.deltaOccupancyGridRequired);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestMapUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comp313p_mapper::RequestMapUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "deltaOccupancyGridRequired: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.deltaOccupancyGridRequired);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATEREQUEST_H
