// Generated by gencpp from file comp313p_mapper/RequestMapUpdateResponse.msg
// DO NOT EDIT!


#ifndef COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATERESPONSE_H
#define COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comp313p_mapper/MapUpdate.h>

namespace comp313p_mapper
{
template <class ContainerAllocator>
struct RequestMapUpdateResponse_
{
  typedef RequestMapUpdateResponse_<ContainerAllocator> Type;

  RequestMapUpdateResponse_()
    : initialMapUpdate()  {
    }
  RequestMapUpdateResponse_(const ContainerAllocator& _alloc)
    : initialMapUpdate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::comp313p_mapper::MapUpdate_<ContainerAllocator>  _initialMapUpdate_type;
  _initialMapUpdate_type initialMapUpdate;





  typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RequestMapUpdateResponse_

typedef ::comp313p_mapper::RequestMapUpdateResponse_<std::allocator<void> > RequestMapUpdateResponse;

typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateResponse > RequestMapUpdateResponsePtr;
typedef boost::shared_ptr< ::comp313p_mapper::RequestMapUpdateResponse const> RequestMapUpdateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comp313p_mapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'comp313p_mapper': ['/home/victor/COMP313P/cw1_ws/src/comp313p/comp313p_mapper/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c38a84a7069507e7645c74bfe20d6807";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc38a84a7069507e7ULL;
  static const uint64_t static_value2 = 0x645c74bfe20d6807ULL;
};

template<class ContainerAllocator>
struct DataType< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comp313p_mapper/RequestMapUpdateResponse";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comp313p_mapper/MapUpdate initialMapUpdate\n\
\n\
================================================================================\n\
MSG: comp313p_mapper/MapUpdate\n\
Header header\n\
\n\
bool isPriorMap\n\
\n\
float32 scale\n\
int16[] extentInCells\n\
float32 resolution\n\
\n\
float32[] occupancyGrid\n\
float32[] deltaOccupancyGrid\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.initialMapUpdate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestMapUpdateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comp313p_mapper::RequestMapUpdateResponse_<ContainerAllocator>& v)
  {
    s << indent << "initialMapUpdate: ";
    s << std::endl;
    Printer< ::comp313p_mapper::MapUpdate_<ContainerAllocator> >::stream(s, indent + "  ", v.initialMapUpdate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATERESPONSE_H
