# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comp313p_mapper/RequestMapUpdateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RequestMapUpdateRequest(genpy.Message):
  _md5sum = "f7f3f7638aa1640753832d43db8a1853"
  _type = "comp313p_mapper/RequestMapUpdateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool deltaOccupancyGridRequired
"""
  __slots__ = ['deltaOccupancyGridRequired']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       deltaOccupancyGridRequired

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestMapUpdateRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.deltaOccupancyGridRequired is None:
        self.deltaOccupancyGridRequired = False
    else:
      self.deltaOccupancyGridRequired = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.deltaOccupancyGridRequired))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.deltaOccupancyGridRequired,) = _get_struct_B().unpack(str[start:end])
      self.deltaOccupancyGridRequired = bool(self.deltaOccupancyGridRequired)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.deltaOccupancyGridRequired))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.deltaOccupancyGridRequired,) = _get_struct_B().unpack(str[start:end])
      self.deltaOccupancyGridRequired = bool(self.deltaOccupancyGridRequired)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comp313p_mapper/RequestMapUpdateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import comp313p_mapper.msg
import std_msgs.msg

class RequestMapUpdateResponse(genpy.Message):
  _md5sum = "c38a84a7069507e7645c74bfe20d6807"
  _type = "comp313p_mapper/RequestMapUpdateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """comp313p_mapper/MapUpdate initialMapUpdate

================================================================================
MSG: comp313p_mapper/MapUpdate
Header header

bool isPriorMap

float32 scale
int16[] extentInCells
float32 resolution

float32[] occupancyGrid
float32[] deltaOccupancyGrid
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['initialMapUpdate']
  _slot_types = ['comp313p_mapper/MapUpdate']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       initialMapUpdate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestMapUpdateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.initialMapUpdate is None:
        self.initialMapUpdate = comp313p_mapper.msg.MapUpdate()
    else:
      self.initialMapUpdate = comp313p_mapper.msg.MapUpdate()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.initialMapUpdate.header.seq, _x.initialMapUpdate.header.stamp.secs, _x.initialMapUpdate.header.stamp.nsecs))
      _x = self.initialMapUpdate.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bf().pack(_x.initialMapUpdate.isPriorMap, _x.initialMapUpdate.scale))
      length = len(self.initialMapUpdate.extentInCells)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.pack(pattern, *self.initialMapUpdate.extentInCells))
      buff.write(_get_struct_f().pack(self.initialMapUpdate.resolution))
      length = len(self.initialMapUpdate.occupancyGrid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.initialMapUpdate.occupancyGrid))
      length = len(self.initialMapUpdate.deltaOccupancyGrid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.initialMapUpdate.deltaOccupancyGrid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.initialMapUpdate is None:
        self.initialMapUpdate = comp313p_mapper.msg.MapUpdate()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.initialMapUpdate.header.seq, _x.initialMapUpdate.header.stamp.secs, _x.initialMapUpdate.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initialMapUpdate.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.initialMapUpdate.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.initialMapUpdate.isPriorMap, _x.initialMapUpdate.scale,) = _get_struct_Bf().unpack(str[start:end])
      self.initialMapUpdate.isPriorMap = bool(self.initialMapUpdate.isPriorMap)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.extentInCells = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (self.initialMapUpdate.resolution,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.occupancyGrid = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.deltaOccupancyGrid = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.initialMapUpdate.header.seq, _x.initialMapUpdate.header.stamp.secs, _x.initialMapUpdate.header.stamp.nsecs))
      _x = self.initialMapUpdate.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bf().pack(_x.initialMapUpdate.isPriorMap, _x.initialMapUpdate.scale))
      length = len(self.initialMapUpdate.extentInCells)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.initialMapUpdate.extentInCells.tostring())
      buff.write(_get_struct_f().pack(self.initialMapUpdate.resolution))
      length = len(self.initialMapUpdate.occupancyGrid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.initialMapUpdate.occupancyGrid.tostring())
      length = len(self.initialMapUpdate.deltaOccupancyGrid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.initialMapUpdate.deltaOccupancyGrid.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.initialMapUpdate is None:
        self.initialMapUpdate = comp313p_mapper.msg.MapUpdate()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.initialMapUpdate.header.seq, _x.initialMapUpdate.header.stamp.secs, _x.initialMapUpdate.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initialMapUpdate.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.initialMapUpdate.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.initialMapUpdate.isPriorMap, _x.initialMapUpdate.scale,) = _get_struct_Bf().unpack(str[start:end])
      self.initialMapUpdate.isPriorMap = bool(self.initialMapUpdate.isPriorMap)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.extentInCells = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      start = end
      end += 4
      (self.initialMapUpdate.resolution,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.occupancyGrid = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.initialMapUpdate.deltaOccupancyGrid = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bf = None
def _get_struct_Bf():
    global _struct_Bf
    if _struct_Bf is None:
        _struct_Bf = struct.Struct("<Bf")
    return _struct_Bf
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
class RequestMapUpdate(object):
  _type          = 'comp313p_mapper/RequestMapUpdate'
  _md5sum = 'e5aa3588d7db3769375365d7ca3672e4'
  _request_class  = RequestMapUpdateRequest
  _response_class = RequestMapUpdateResponse
