// Generated by gencpp from file comp313p_mapper/RequestMapUpdate.msg
// DO NOT EDIT!


#ifndef COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATE_H
#define COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATE_H

#include <ros/service_traits.h>


#include <comp313p_mapper/RequestMapUpdateRequest.h>
#include <comp313p_mapper/RequestMapUpdateResponse.h>


namespace comp313p_mapper
{

struct RequestMapUpdate
{

typedef RequestMapUpdateRequest Request;
typedef RequestMapUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestMapUpdate
} // namespace comp313p_mapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comp313p_mapper::RequestMapUpdate > {
  static const char* value()
  {
    return "e5aa3588d7db3769375365d7ca3672e4";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdate&) { return value(); }
};

template<>
struct DataType< ::comp313p_mapper::RequestMapUpdate > {
  static const char* value()
  {
    return "comp313p_mapper/RequestMapUpdate";
  }

  static const char* value(const ::comp313p_mapper::RequestMapUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::comp313p_mapper::RequestMapUpdateRequest> should match 
// service_traits::MD5Sum< ::comp313p_mapper::RequestMapUpdate > 
template<>
struct MD5Sum< ::comp313p_mapper::RequestMapUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comp313p_mapper::RequestMapUpdate >::value();
  }
  static const char* value(const ::comp313p_mapper::RequestMapUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comp313p_mapper::RequestMapUpdateRequest> should match 
// service_traits::DataType< ::comp313p_mapper::RequestMapUpdate > 
template<>
struct DataType< ::comp313p_mapper::RequestMapUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::comp313p_mapper::RequestMapUpdate >::value();
  }
  static const char* value(const ::comp313p_mapper::RequestMapUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comp313p_mapper::RequestMapUpdateResponse> should match 
// service_traits::MD5Sum< ::comp313p_mapper::RequestMapUpdate > 
template<>
struct MD5Sum< ::comp313p_mapper::RequestMapUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comp313p_mapper::RequestMapUpdate >::value();
  }
  static const char* value(const ::comp313p_mapper::RequestMapUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comp313p_mapper::RequestMapUpdateResponse> should match 
// service_traits::DataType< ::comp313p_mapper::RequestMapUpdate > 
template<>
struct DataType< ::comp313p_mapper::RequestMapUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::comp313p_mapper::RequestMapUpdate >::value();
  }
  static const char* value(const ::comp313p_mapper::RequestMapUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMP313P_MAPPER_MESSAGE_REQUESTMAPUPDATE_H
